apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: three-tier-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/hakanbayraktar/three-tier-devops-platform.git'
    targetRevision: main
    path: k8s/eks
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: three-tier-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
