apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: three-tier-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "SuperSecretPass123!"
  MYSQL_PASSWORD: "SchoolUserPass456!"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: three-tier-app
data:
  MYSQL_DATABASE: "school"
  MYSQL_USER: "school_user"
