apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/00-namespace.yaml
  - ../base/01-mysql-secrets.yaml
  - ../base/03-mysql-deployment.yaml
  - ../base/04-backend.yaml
  - ../base/05-frontend.yaml
  - 01-storageclass-gp3.yaml
  - 02-mysql-pvc-ebs.yaml
  - 03-ingress-alb.yaml

images:
  - name: three-tier-backend
    newName: three-tier-backend
    newTag: latest
  - name: three-tier-frontend
    newName: three-tier-frontend
    newTag: latest
